In [1]:
import pandas as pd

In [7]:
df1 = pd.ExcelFile('../../../data/dataset_tesis/twitter/df1.xlsx')

In [8]:
def mergeData(df):
    # Creamos un diccionario con cada hoja del archivo
    ndf = {sheet_name: df.parse(sheet_name) for sheet_name in df.sheet_names}
    # Variable para almacenamiento de dataframes
    array = []
    for key in ndf.keys():
        array.append(pd.DataFrame(ndf[key]))
    return array

In [9]:
df1t = pd.concat(mergeData(df1))
df1t.columns

Index(['Date', 'Screen Name', 'Full Name', 'Tweet Text', 'Tweet ID', 'Link(s)',
       'Media', 'Location', 'Retweets', 'Favorites', 'App', 'Followers',
       'Follows', 'Listed', 'Verfied', 'User Since', 'Location.1', 'Bio',
       'Website', 'Timezone', 'Profile Image'],
      dtype='object')

In [11]:
df = df1t.drop(['Link(s)','Media','Location','Verfied','Location.1','Website','Timezone','Profile Image','Bio'],axis=1)

In [13]:
df = df.dropna()
df = df.drop_duplicates(subset=['Tweet Text'])

In [14]:
df.shape

(1542, 12)

In [15]:
dfm = pd.read_csv('../../../data/dataset_tesis/twitter/mergeData.csv')

In [16]:
dfm

,Date,Screen Name,Full Name,Tweet Text,Tweet ID,Retweets,Favorites,App,Followers,Follows,Listed,User Since
0,2020-10-24 14:05:16,@IpasMEX,Ipas M√©xico,"""Cuando Rub√≠ es asesinada por su novio, Marise...",1320109126593044481,0,4,Twitter for iPhone,4021,643,42,41771.6843402778
1,2020-10-24 06:00:01,@_interseccional,INTERSECCIONAL üè≥Ô∏è‚Äçüåà üè≥Ô∏è‚Äç‚ößÔ∏è,En diferentes partes de mundoüåéest√°n asesinando...,1319987009104965634,1,0,Twitter Web App,207,214,3,43816.5469907407
2,2020-10-24 05:03:52,@VocesDLAusencia,Voces De La Ausencia,"Laura Melisa Vel√°zquez S√°nchez tenia 20, cuand...",1319972876674584577,57,40,Twitter for iPhone,2794,246,5,43315.3385069444
3,2020-10-24 04:37:26,@VocesDLAusencia,Voces De La Ausencia,"Lizbeth Mendoza G√≥mez naci√≥ el 18/10/1998, ten...",1319966225414410240,14,23,Twitter for iPhone,2794,246,5,43315.3385069444
4,2020-10-24 02:00:46,@_Seleneesgenial,Selene es lo m√°ximo.,Acabo de terminar de ver #LasTresMuertesDeMari...,1319926797702733824,0,0,Twitter for Android,318,70,0,41328.7664236111
...,...,...,...,...,...,...,...,...,...,...,...,...
2982,2021-06-07 10:38:48,@wdc00027,Wendy Casta√±o,Persona m√°s hip√≥crita que usted no he conocido...,1401956825600307203,0,1,Twitter for iPhone,14,15,0,2021-05-25 17:26:26
2983,2021-06-07 10:30:49,@StepHarder_,Mich,Como payasa qued√©.,1401954816012734468,0,0,Twitter for Android,74,444,0,2017-04-02 14:59:33
2984,2021-06-07 10:28:01,@bastia_agustin,ùï∞ùñë ùï∏ùñÜùñôùñÜùñôùñÜùñì,"Me da risa la payasa esta, termino siendo una ...",1401954111118053378,0,0,Twitter for Android,171,197,0,2017-04-01 10:51:12
2985,2021-06-07 10:23:48,@irene78975696,ireüíå,Todo mi verano depende de c√≥mo me salgan los e...,1401953049078374407,1,6,Twitter for iPhone,45,158,0,2018-12-25 15:41:23
2986,2021-06-07 10:22:09,@MalditaSoaUlls,‚Ñíùí∂‚Ñ≥ùí∂ùìÅùíπùíæùíæùíæùìâùí∂ùí∞ùìÅùìÅùìà üíÄ,Gente culi√° payasa wn JAJJAJJAJAJAJA,1401952633070538755,0,2,Twitter for Android,2792,2738,2,2015-02-23 09:56:43

In [17]:
df

,Date,Screen Name,Full Name,Tweet Text,Tweet ID,Retweets,Favorites,App,Followers,Follows,Listed,User Since
0,2021-06-22 19:16:38,@Leon_FC,Grafito/Carboncillo,"¬°¬°Una Caperucit... Fin de mundo, dir√≠a mi abue...",1407492758173065218,0,0,Twitter Web App,2360,994,24,2010-02-27 18:01:06
1,2021-06-22 19:15:56,@cnerwing,reinaldo ardila,"La marrana Alarcon de FECODE, no se fue por am...",1407492582838525952,0,0,Twitter for iPhone,3159,2983,3,2013-11-23 23:00:43
2,2021-06-22 19:06:56,@0rangemint,Angie‚ùÅ‚Å∑,La gente de orz comportandose c√≥mo que si yo n...,1407490317461475332,0,0,Twitter for Android,1486,756,26,2012-09-02 18:16:17
3,2021-06-22 19:04:17,@Faacu_Rs,Faacurs,Solo dios sabe lo cochina y degenerada que deb...,1407489652542607368,0,0,Twitter for Android,103,61,2,2011-12-30 18:07:42
4,2021-06-22 19:00:05,@Victtoria713,Victoria S√°nchez,üíî ¬°La COCHINA realidad de la patria! Patria qu...,1407488595917611010,0,1,Twitter for Android,171,641,2,2009-05-11 08:37:56
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2021-06-22 14:14:34,@Mely_Aramayo,@LaPutaAma,Estoy siendo una perra,1407446940028186630,0,0,Twitter for Android,6,151,0,2021-06-21 07:00:23
96,2021-06-22 14:14:32,@ChiyoIwasaki,‚Ä¢ Jaz ‚Ä¢,Dos personas me dijeron que estoy mas culona.....,1407446931023052806,0,2,Twitter for Android,369,299,0,2019-12-31 09:20:48
97,2021-06-22 14:14:19,@villafanezlu,Luüåª,"Mood Nathy Peluso: una perra sorprendente, cur...",1407446878762024964,0,0,Twitter for Android,77,288,0,2016-09-22 14:08:05
98,2021-06-22 14:14:13,@fedehenrig,Fede Henriquez Rigoni,Queda una Perra y sus dos Cachorros para regal...,1407446850894974985,0,0,Twitter for iPhone,1242,1292,27,2010-05-07 23:16:23
99,2021-06-22 14:13:57,@TitoMorenoLope2,RICHAR,Su perra mare cuesta un ü•öestudiar lic en gastr...,1407446785933541380,0,0,Twitter for iPhone,485,519,1,2016-07-10 16:45:55

In [19]:
dfn = pd.concat([df, dfm])

In [20]:
dfn.shape

(4529, 12)

In [21]:
dfn = dfn.dropna()
dfn = dfn.drop_duplicates(subset=['Tweet Text'])

In [22]:
dfn.shape

(4527, 12)

In [23]:
dfn.to_csv('../../../data/dataset_tesis/twitter/mergeData2.csv', index=False)